language: cpp

git:
  depth: 1
  
sudo: required
dist: trusty

install:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-install.sh

script:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-build.sh

matrix:
    include:
        - os: linux
          compiler: gcc
          cache: ccache
        - os: linux
          compiler: clang
        - os: osx
          osx_image: xcode10.1
          env:
            - HOMEBREW_NO_AUTO_UPDATE=1
            - HOMEBREW_NO_ANALYTICS=1
          cache:
            directories:
              - $HOME/Library/Caches/Homebrew
              - /usr/local/Homebrew
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".*\.git.*" -delete; fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITNAME"
  - git config --local user.email "$GITEMAIL"
  - export TRAVIS_TAG="continuous"
  - git tag -f $TRAVIS_TAG
  - bash ci-scripts/$TRAVIS_OS_NAME/otx-buildpkg.sh

after_success:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          chmod +x ci-scripts/$TRAVIS_OS_NAME/opentoonz-deploy.sh
          ci-scripts/$TRAVIS_OS_NAME/opentoonz-deploy.sh
      fi
    
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
